### ISSUE TITLE
Main page can't show all article

### ISSUE THREAD

**Issue by chengsixgoold** [Reedyn/Saga#102]
My website main page article count more than 20, but saga only show the newest 20 . the Load More button is miss.so i wonder to know why? it is a bug? my blog site :chengsixgold.com & you can try.

**Comment by Reedyn** [comment]
Did you download one of the releases or did you download the project? The master branch is not stable

**Comment by Reedyn** [comment]
It does look to be a bug. I have the same problem on my own blog running the theme, so it's most likely to due to a new version of Ghost clashing with it. I'll have a fix out after I get home from my vacation, in the meantime either try an older version of Ghost or another theme.

**Comment by chengsixgoold** [comment]
OK, just forget the bug and have fun in the vacation . i have no problem and thanks.
