### ISSUE TITLE
Click Load More one more time will show blank page without blog content

### ISSUE THREAD

**Issue by chengsixgoold** [Reedyn/Saga#103]
I click load more twice and the page show blank without blog content . the reason why i click twice is that my network is slow. you can test it in this site:[chengsixgold.com](chengsixgold.com)

<img width="1280" alt="screen shot 2018-06-30 at 3 30 37 pm" src="https://user-images.githubusercontent.com/11493853/42122856-bb02cab4-7c7a-11e8-9156-82adf5292a58.png">

**Comment by Reedyn** [comment]
Can you see if my changes in ae64cc8217a9a640ce5f7c607885047b63999624 solved this?

**Comment by chengsixgoold** [comment]
yeah，it work. thanks 💯

**Comment by Reedyn** [comment]
@chengsixgoold Great. A pre-release of the 2.0 release will be out soon(ish)
