### ISSUE TITLE
Menu-system

### ISSUE THREAD

**Issue by Reedyn** [Reedyn/Saga#37]
As this will be supported in the future by Ghost I thought it'd only be good to start to think on how to implement this.

I'm not looking into integrating anything complex, ideally it wouldn't even be nested.
- Should be simple (ideally something like the current social-media buttons).
- Shouldn't be collapsed in mobile-view _(Not a big fan of menus you can't get an overview on without clicking first)_
- Should support all Ghost's standard menu features (except perhaps the nesting)

I'm interested to know how others feel about this and how you would like to get menus integrated. @seanichol @PxlBuzzard

**Comment by Reedyn** [comment]
Currently keeping an eye on what is going on in TryGhost/Ghost#4535 before settling on what to do with this.

**Comment by seanichol** [comment]
Personally speaking, I'l never use a menu beyond linking my top tag/category pages and an "About" page. So, maybe three to four links in the header... not a big fan of these "mega-menus" you see everywhere.

**Comment by Reedyn** [comment]
Yeah, with that I agree wholeheartedly :)

My choices right now are between the following

### 1. Icon based menu
Have the same design as the current menu has. The user will have to find the corresponding icon they want to display, copy the character and then paste that into the display-name of the menu item (in the settings). The theme then displays that character using the icon-font.

That would gives the same style as we have right now, and it would be easier than we have right now, but it would give some drawbacks for some people.

### 2. Name based menu
New design for menu, not sure how this would look but would figure out something.

Not an icon based but uses a normal font. This has the advantage that new users can easily swap between themes without adapting their menu.

### 3. Partial based menu

As it is right now, this is something I'd like to avoid, especially since option 1 is easier :)

**Comment by shadowframe** [comment]
icon based menu plz. :)

**Comment by Bizzi-Body** [comment]
@Reedyn - You mention... "Have the same design as the current menu has."  Menu?  Is there already a menu of sorts?

Anyhow - my preference (for what it's worth) is that the menu should be stupid simple.  
Agree, by default the menu should be expanded for mobile.  
Icons and text - It's easy for icon meaning to get lost in translation, or the icon could just be rubbish.  Having the text as well would keep things clear.

**Comment by Reedyn** [comment]
@Bizzi-Body What I'm referring to is the icon-style menu at the top right. It can be accessed and changed via the `partials/links.hbs`-file.

What I'm planning to do is atleast allow the option of changing the menu via the now build in system. Not sure exactly as to how to do that yet as it can be a pain to handle the icons.

**Comment by Bizzi-Body** [comment]
Ah.  Got-yah.  I suppose the problem is that there are only two fields in the menu feature - title and link.

How about if people just insert any html into the menu?

i.e.  
Title = <i class="fa fa-user"></i>Contact Us
Link = /contactus/

As a MFP it would get you up and running quickly and give you time to see how the feature is used before stressing about putting effort into something that might not be required.

**Comment by Reedyn** [comment]
The issue is that I don't have control over how the menu system is used. And I want the theme to work out of the box with ease.

Saga with Ghosts implementation of their menu system should be able to handle many menu-items with both long and short names. That would mean going away from the very minimalist icon-based system that it currently has.
