### ISSUE TITLE
Lists not working properly

### ISSUE THREAD

**Issue by kjullien** [Reedyn/Saga#55]
I haven't tested it with any other themes so this could be a Ghost bug, but the lists (using * and - for new items) will work like 1/5 of the time, I usually just end up adding them in HTML.

**Comment by Reedyn** [comment]
If they work in HTML then it's a Ghost issue since Saga is just resonsible
for styling the HTML :)

**Comment by Reedyn** [comment]
If they work in HTML then it's a Ghost issue since Saga is just resonsible
for styling the HTML :)

Check your markdown for errors. When using lists it requires an empty row before and after

```markdown
# List that won't display properly
* listitem
* listitem
* listitem
* listitem
```
```markdown
# List that will display properly

* listitem
* listitem
* listitem
* listitem
```
