### ISSUE TITLE
Graceful degradation?

### ISSUE THREAD

**Issue by synth3tk** [Reedyn/Saga#59]
Any plans to make the theme work with JS disabled?

**Comment by Reedyn** [comment]
Yes, at the moment it is basically just the feed that doesn't work properly without JS. I cannot give a timeline when it will be done though

**Comment by synth3tk** [comment]
Ok, thanks. Was just wondering if it was in the works. Loving the theme otherwise!

**Comment by Reedyn** [comment]
Closing this as duplicate of #38
