### ISSUE TITLE
Image size hash is not active when image is placed in a quotation

### ISSUE THREAD

**Issue by Bizzi-Body** [Reedyn/Saga#60]
Example of markup

`> ![Black icon blue text](/content/images/2015/04/FontAwesomeUIButton4.png#small)`

Notice that the content is within a quotation.  The #small image selector is ignored.  This could just be the way markup is, or the way Ghost is.

**Comment by Reedyn** [comment]
It has to do with the theme. Working as was intended as changing the size of the images involves changing the position as well. 

Although, that more applies to the wider alternatives (as they need to fit inside the total width of the `blockquote` while `#small` doesn't. I will consider this.
