### ISSUE TITLE
links, emphasize, and italic (markdown or html) showing like superscript

### ISSUE THREAD

**Issue by audientmusic** [Reedyn/Saga#71]
I have fallen in love with this saga theme, firstly.  I have run into an issue, though.  Anytime I use a link or emphasis, or italic, the text shows "higher" than the text around it.  I've tried using the ghost markdown language as well as straight HTML coding to try to get it to work, but to no avail.  Have you seen this before?  It's the only thing I've run into in this otherwise excellent theme.  Here is an example (it's stupid)
http://audientmusic.ghost.io/2015/08/30/aria-giovanni/
Thanks
Rob

**Comment by Reedyn** [comment]
Try to add an empty line before and after images in the markdown. 

Instead of:

```
![]()
text
![]()
```

write like this

```
![]()

text

![]()
```
