### ISSUE TITLE
not work in firefox 64bit windows version

### ISSUE THREAD

**Issue by qiaoyan** [Reedyn/Saga#80]
Hi, thanks for your sharing. I am not sure it's from ghost or saga.

**Comment by Reedyn** [comment]
Can you provide more details? An URL to your blog would be helpful, and the exact version of Firefox you're using.

**Comment by qiaoyan** [comment]
hi, website http://www.zymmm.com , firefox 43.0.2 windows 64bit, download url:  https://download.mozilla.org/?product=firefox-43.0.2-SSL&os=win64&lang=en-US
items are invisible but placeholders are there and clickable. Thanks.

**Comment by Reedyn** [comment]
It has something to do with jQuery not loading. The url `http://apps.bdimg.com` has blocked requests. And perhaps it's because Firefox is more restrictive than Chrome.

I would try to use a different CDN for jQuery and FontAwesome and see if that solves it.
