### ISSUE TITLE
Saga 2.0

### ISSUE THREAD

**Issue by Reedyn** [Reedyn/Saga#87]
This release intends to lay out the groundwork for the future of the theme. The entire theme will be rewritten where needed.
## Summary
- New CSS-structure with a more clear hierarchy with the naming.
- New Sass structure using the 7-1 pattern
- Major optimizations
  - Make the theme load without JavaScript (especially for mobile as Masonry isn't really needed there anyway)
  - Remove iconfonts and replace with SVG-icons (Users can add their own iconfont if they want
  - Smarter scripting
- Some changes in the design, such as adding navigation menu and building in support for every page to have cover image.

**Comment by fudaming** [comment]
<img width="515" alt="2017-09-04 22 27 23" src="https://user-images.githubusercontent.com/19947521/30042593-43e57b48-91c0-11e7-876d-4b451a99acfa.png">

**Comment by Reedyn** [comment]
@fudaming 2.0 is far off being ready for use. Use the official releases for now.

**Comment by Reedyn** [comment]
Closing this Epic and moved to GitHubs Project structure
