### ISSUE TITLE
"Load more" button throwing error

### ISSUE THREAD

**Issue by 84896150** [Reedyn/Saga#93]
The "load more" button in the index page was throwing an error upon being pressed. Issue was traced to line 218 of scripts.js.
Uncaught TypeError: Cannot read property 'substring' of undefined
Ghost Version：0.10.0
Browser/OS: Chrome 54.0.2840.8

<img width="537" alt="screen shot 2016-09-16 at 10 32 41" src="https://cloud.githubusercontent.com/assets/3245204/18579108/17f6b71e-7c26-11e6-8aaf-8c2d1697f899.jpg" style="max-width:100%;">

**Comment by perdix** [comment]
Same issue here. Any idea how to fix this?
![screen shot 2016-10-12 at 14 53 42](https://cloud.githubusercontent.com/assets/1526654/19310720/c7f94ae0-908b-11e6-9320-3413d36b8294.png)

**Comment by Neffez** [comment]
This will fix it.
```
var self = this;
$.get(self.nextLink, function(data){ 
    // Append all posts to #content
    var posts = $(data).find('.post');
    $.each(posts,function(){
        $(self).css('opacity', 0);
    });
    $masonry.append(posts);
    // Change nextLink to next page
    $('#feed').imagesLoaded(function(){
    self.pageNum++;
    self.nextLink = self.nextLink.substring(0, self.nextLink.indexOf('page/'));
    self.nextLink += 'page/'+(self.pageNum+1);

    // Remove button if last page else move the button to end of #content
    if(self.pageNum < self.max) {
        $('#loadmore').insertAfter($('#feed .post:last'));
        $('#loadmore a').html("Load more <i class='fa fa-plus-circle'></i>");
    } else {
            $('#loadmore').remove();
    }
        $masonry.masonry('appended', posts);
    });
});

```
