### ISSUE TITLE
Investigate alternatives to Masonry

### ISSUE THREAD

**Issue by Reedyn** [Reedyn/Saga#97]
Investigate alternatives to Masonry based on CSS Grid

**Comment by Reedyn** [comment]
Tested out two different versions of CSS Grid both based on `auto-fit` and `grid-auto-flow: dense;`

[First version keeps the aspect ratio of the images intact](https://codepen.io/Reedyn/pen/ZJRmBp/) and has a more sparse layout because of it.
[![](https://i.imgur.com/Phi5SLw.jpg)](https://codepen.io/Reedyn/pen/ZJRmBp/)

[The second has a set max height](https://codepen.io/Reedyn/full/ZJRmBp/) of the images (similar to [Casper](https://demo.ghost.io)
[![](https://i.imgur.com/hEnGGjM.jpg)](https://codepen.io/Reedyn/full/ZJRmBp/)

**Comment by synth3tk** [comment]
They're both the same Pen. Should the first one be a different URL?

**Comment by Reedyn** [comment]
@synth3tk Fixed now

**Comment by Reedyn** [comment]
I went with a CSS Grid based solution instead. See screenshot of how the new design will look.

![image](https://user-images.githubusercontent.com/947063/42658293-37d5ea5e-8625-11e8-99f1-ae87e42ebb16.png)
